# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Assembly-CSharp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore packages
      run: nuget restore Assembly-CSharp.csproj

    - name: Build with MSBuild
      run: msbuild Assembly-CSharp.csproj /p:Configuration=Release
    - name: Upload built DLL
      uses: actions/upload-artifact@v4
      with:
        name: Assembly-CSharp.dll
        path: bin\Release\net462\Assembly-CSharp.dll

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: built-dll

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: Assembly-CSharp.dll
        tag_name: auto-${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
