# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Assembly-CSharp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore packages
      run: nuget restore Assembly-CSharp.csproj

    - name: Build with MSBuild
      run: msbuild Assembly-CSharp.csproj /p:Configuration=Release
    - name: Upload built DLL
      uses: actions/upload-artifact@v4
      with:
        name: Assembly-CSharp.dll
        path: bin\Release\net462\Assembly-CSharp.dll

    - name: Get short hash
      id: short_sha
      run: echo "::set-output name=sha::$(expr substr ${{ github.sha }} 1 7)"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto-${{ steps.short_sha.outputs.sha }}
        prerelease: true
        files: bin\Release\net462\Assembly-CSharp.dll
